### ISSUE TITLE
Week 9 ready for review

### ISSUE THREAD

**Issue by eferr216** [eferr216/specificPet#3]
@pawaitemadisoncollege Week 9 is ready for review!

**Comment by pawaitemadisoncollege** [comment]
Hi @eferr216  - the code looks to be on target for providing pets as a restful endpoint. Can you share a screenshot showing this is working as expected - either calling the endpoint in the browser or through postman or soapui, so that I can confirm. Thanks!  See the steps for submitting week 9 below. 

<img width="1145" alt="Screenshot 2024-12-08 at 8 58 40 AM" src="https://github.com/user-attachments/assets/08aa68c6-bd75-41a3-8cfc-b9aac51c0f66">


**Week 9: not yet.**

**Comment by eferr216** [comment]
Sorry here goes!
![week_9_api_w_id](https://github.com/user-attachments/assets/15cb5e59-131a-46b4-a1d9-fa03d64429dd)
![week_9_api_w_no_id](https://github.com/user-attachments/assets/7ee9d37a-9433-422b-beed-2bfb69825a95)

**Comment by pawaitemadisoncollege** [comment]
Hi @eferr216 - this is a good start creating a restful endpoint with java code. You followed best practices for naming the resource: pets.

Considerations for future work  - no need to produce json manually. One way is to use jackson: https://mkyong.com/java/convert-java-objects-to-json-with-jackson/#convert-java-object-to-json-using-jackson

**week 9: met.**
